set-option global ui_options ncurses_status_on_top=true

add-highlighter global/ show-matching
add-highlighter global/ number-lines

map global normal = <a-i>
map global normal a '*%s<ret>' -docstring 'select all'

hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec <esc>
}}

