set nocompatible

colorscheme molokai

syntax on
filetype plugin indent on

set hidden
set lazyredraw
set ttyfast

set history=999
set undolevels=999
set autoread

set nobackup
set nowritebackup
set noswapfile

set gdefault
set magic
set hlsearch
set incsearch
set ignorecase smartcase
set clipboard=unnamedplus

set cursorline
set number
set showmatch
set title

set scrolloff=5
set sidescrolloff=7
set sidescroll=1

set expandtab

set softtabstop=2
set tabstop=2
set shiftwidth=2
set smarttab
set backspace=2
