#!/usr/bin/env sh

diary="$HOME/warm/notes/diary"
if ! [[ -d "$diary" ]]; then
  echo "Diary folder('$d') does not exist!" 2>&1
  exit 1
fi

today="$(date +%Y-%m-%d)"
f="$diary/$today.md"

if ! [ -e "$f" ]; then
  ( echo -n "# "; date "+%d %B %Y, %A" ) >> "$f"
fi

ranger --selectfile "$f"
