#!/usr/bin/env sh

STRETCH_DURATION_SECONDS=20
STRETCH_INTERVAL_MINUTES=10

REST_RECURRENCE=6
REST_DURATION_MINUTES=10

if ! command -v yad >/dev/null 2>&1; then
  echo "This script requires a 'yad' executable on PATH. Exiting." 2>&1
  exit 1
fi

rest_remaining=$REST_RECURRENCE
while true; do
  wait_secs="$(( STRETCH_INTERVAL_MINUTES * 60 - STRETCH_DURATION_SECONDS ))"
  echo "Working for $wait_secs seconds."
  pv /dev/zero -L 1 -s "$wait_secs" -p | head -c "$wait_secs"

  rest_remaining=$(( rest_remaining - 1 ))
  if [[ $rest_remaining -gt 0 ]]; then
    echo "Stretching for $STRETCH_DURATION_SECONDS seconds."
    yad \
      --info --title "ergo" \
      --timeout-indicator bottom --center --on-top --sticky --no-buttons --no-escape \
      --text="<span font='32'>Strech for $STRETCH_DURATION_SECONDS seconds.</span>" \
      --text-align "center" --timeout="$STRETCH_DURATION_SECONDS"
  else
    echo "Resting for $REST_DURATION_MINUTES minutes."
    yad \
      --info --title "ergo" \
      --timeout-indicator bottom --center --on-top --sticky --no-buttons --no-escape \
      --text='<span font="32">Rest up!</span>' --text-align "center" \
      --timeout="$(( REST_DURATION_MINUTES * 60 ))"
    rest_remaining=$REST_RECURRENCE
  fi
done
